services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-project-test
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    networks:
      - mlops-net

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_app-project-test
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - mlops-net
  
networks:
  mlops-net:
    driver: bridge