FROM python:3.13
# Install uv (modern Python packaging tool)
RUN pip install uv

WORKDIR /app
COPY serving/* .

# Sync dependencies using uv
RUN uv sync --frozen


COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]