FROM python:3.13
# Install uv (modern Python packaging tool)
RUN pip install uv

WORKDIR /app
COPY serving/* .

# Sync dependencies using uv
RUN uv sync --frozen
RUN apt-get update && apt-get install -y gosu && rm -rf /var/lib/apt/lists/*


# Use uv to run the app within the virtual environment
CMD ["uv", "run", "python", "app.py"]