name: 3 - Continuous Staging
run-name: "${{ github.workflow }}"

permissions: write-all

on:
  # Runs when the previous stage finished
  workflow_run:
    workflows: ["2 - Continuous Delivery"]
    types: [completed]

  workflow_dispatch:

env:
  REGISTRY: ${{ vars.REGISTRY }}
  MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
  MLFLOW_EXPERIMENT_NAME: ${{ vars.MLFLOW_EXPERIMENT_NAME }}
  MLFLOW_MODEL_NAME: ${{ vars.MLFLOW_MODEL_NAME }}

jobs:
  stage-tests:
    # Run only if previous stage finished successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }
      - run: pip install uv

      # Log in to GitHub Container Registry (GHCR)
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker pull ${{ env.REGISTRY }}/mcdoritos/laia-taxi_trip/serving:staging

      # Cleanup old serving container if it exists
      - name: Cleanup old serving container
        run: |
          docker rm -f serving-app 2>/dev/null || true

      - name: Start serving container
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}
          MODEL_ALIAS: ${{ github.sha }}
          MLFLOW_MODEL_NAME: ${{ env.MLFLOW_MODEL_NAME }}
        run: |
          docker run -d \
            --name serving-app \
            -p 9001:8080 \
            -v $(pwd)/logs:/app/logs \
            -e LOG_DIR=/app/logs \
            -e MLFLOW_TRACKING_URI \
            -e MODEL_ALIAS \
            -e MLFLOW_MODEL_NAME \
            ${{ env.REGISTRY }}/mcdoritos/laia-taxi_trip/serving:staging

      # Run E2E tests
      - name: Run Staging tests
        env:
          FLASK_BASE_URL: http://localhost:9001
        run: uv run pytest tests/test_e2e.py -v

      # --- NEW STEP TO FIX PERMISSIONS ---
      # This runs even if tests fail (if: always)
      # It changes ownership of the 'logs' directory back to the runner user
      - name: Fix log permissions
        if: always()
        run: |
          docker run --rm \
            -v $(pwd)/logs:/clean_logs \
            alpine sh -c "chown -R $(id -u):$(id -g) /clean_logs"
      

      # Tag the serving image with production tag
      - name: Push production container tag
        run: |
          docker tag ${{ env.REGISTRY }}/mcdoritos/laia-taxi_trip/serving:staging \
                     ${{ env.REGISTRY }}/mcdoritos/laia-taxi_trip/serving:production
          docker push ${{ env.REGISTRY }}/mcdoritos/laia-taxi_trip/serving:production
